#!/usr/bin/env bash

###############################################################################
# Formats ipython notebooks with tensorflow-docs nbformat tool.
#
# Usage:
#     dev_tools/nbfmt [--apply]
#
# Without '--apply', the diff that would be applied is printed and the exit
# status is 1 if there are any changes or else 0 if no changes are needed.
#
# With '--apply', the exit status is 0 and the changed files are actually
# reformatted.
#
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

# Check if cirq/check/nbformat exists, if not grab it.
if [[ ! -f dev_tools/nbformat ]]; then
  wget https://raw.githubusercontent.com/quantumlib/Cirq/master/check/nbformat -P dev_tools/
  chmod u+x dev_tools/nbformat
fi

# Run the formatter.
dev_tools/nbformat "$@"
