#!/usr/bin/env bash

###############################################################################
# Formats ipython notebooks with tensorflow-docs nbformat tool.
#
# Usage:
#     dev_tools/nbfmt [--apply]
#
# Without '--apply', the diff that would be applied is printed and the exit
# status is 1 if there are any changes or else 0 if no changes are needed.
#
# With '--apply', the exit status is 0 and the changed files are actually
# reformatted.
#
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

# Check if cirq/check/nbformat exists, if not grab it.
if [[ ! -f dev_tools/nbformat ]]; then
  wget https://raw.githubusercontent.com/quantumlib/Cirq/master/check/nbformat -P dev_tools/
  chmod u+x dev_tools/nbformat
fi

# Check if tensorflow-docs.txt requirements file exists, if not grab it.
if [[ ! -f dev_tools/tensorflow-docs.txt ]]; then
  wget https://raw.githubusercontent.com/quantumlib/Cirq/master/dev_tools/requirements/deps/tensorflow-docs.txt -P dev_tools/
  pip install -r dev_tools/tensorflow-docs.txt
fi

# Run the formatter.
result=$(dev_tools/nbformat "$@")
status=$?

# Make sure error message references right file.
result=${result//"check/nbformat"/"dev_tools/nbfmt"}
printf '%s\n' "${result[@]}"
exit $status
